version: 2
jobs:
  build:
    working_directory: /docker-hello
    docker:
      - image: docker:17.05.0-ce-git  #Docker in docker 
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - deploy:
          name: Push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker build -t docker-hello:$TAG .
            docker tag docker-hello $DOCKER_HUB_USER_ID/docker-hello:$TAG
            docker push $DOCKER_HUB_USER_ID/docker-hello:$TAG